-- Migration: Add profile, study, and progress fields to users table
-- Run this in Supabase SQL Editor

-- Personal fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS university VARCHAR;

-- Study profile
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_exam VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS study_hours_per_day INTEGER DEFAULT 4;
ALTER TABLE users ADD COLUMN IF NOT EXISTS specialty VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subject_priority JSONB DEFAULT '[]'::jsonb;

-- Progress / gamification
ALTER TABLE users ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_questions INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_correct INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS study_time_minutes INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS badges JSONB DEFAULT '[]'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subject_stats JSONB DEFAULT '[]'::jsonb;
